FROM node:5.12.0

#update the apt-get packages
RUN apt-get update

#fix locales to be UTF-8
RUN apt-get -y install locales
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8

#config npm
COPY ./.npmrc /root/.npmrc

# add jenkins user (needs to match the <docker.user> value passed to the jenkins job)
RUN adduser --disabled-password --uid=498 --gecos '' jenkins

# add dev user for tests default value in pom.xml
RUN adduser --disabled-password --uid=1000 --gecos '' dp_dev

WORKDIR /data-prep

CMD ["bash"]
