FROM dockerfile/nodejs-bower-gulp
#update the apt-get packages
RUN apt-get update

#install ruby
RUN apt-get -y install ruby1.9.1

#install gem
RUN wget http://production.cf.rubygems.org/rubygems/rubygems-2.4.6.zip
RUN unzip rubygems-2.4.6.zip -d gem
RUN cd gem/rubygems-2.4.6 && ruby setup.rb

#install saas
RUN gem install sass

#install fontconfig to fix some phantom test engine issue
#https://github.com/karma-runner/karma-phantomjs-launcher/issues/31#issuecomment-60698359
RUN apt-get -y install libfontconfig

WORKDIR /dataprep-webapp

CMD ["bash"]