ORIGINAL_HOST=10.42.10.99
ORIGINAL_PORT=8081
JS_FILE=`ls /var/www/scripts/app*`
JS_FILE_BACKUP=$JS_FILE.orig
cd /var/www/scripts
cp $JS_FILE $JS_FILE_BACKUP && sed s/$ORIGINAL_HOST:$ORIGINAL_PORT/$API_PORT_8888_TCP_ADDR:$API_PORT_8888_TCP_PORT/g $JS_FILE_BACKUP > $JS_FILE

